/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'idAudit',
    'idResource',
    'idUser',
    'metadata',
    'occurredAt',
    'requestId',
    'resourceName',
    'resourceType',
    'userName',
    'userRole',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column({ isPrimary: true })
  declare idAudit: string
  @column()
  declare idResource: string | null
  @column()
  declare idUser: string | null
  @column()
  declare metadata: any
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare requestId: string | null
  @column()
  declare resourceName: string
  @column()
  declare resourceType: string
  @column()
  declare userName: string
  @column()
  declare userRole: string
}

export class CropSchema extends BaseModel {
  static $columns = ['createdAt', 'idCrop', 'name', 'normalizedName', 'updatedAt'] as const
  $columns = CropSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idCrop: string
  @column()
  declare name: string
  @column()
  declare normalizedName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FarmAreaEventSchema extends BaseModel {
  static $columns = [
    'idFarm',
    'idFarmAreaEvent',
    'idProducer',
    'newTotalArea',
    'occurredAt',
    'previousTotalArea',
  ] as const
  $columns = FarmAreaEventSchema.$columns
  @column()
  declare idFarm: string | null
  @column({ isPrimary: true })
  declare idFarmAreaEvent: string
  @column()
  declare idProducer: string
  @column()
  declare newTotalArea: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare previousTotalArea: string
}

export class FarmSchema extends BaseModel {
  static $columns = [
    'agriculturalArea',
    'city',
    'createdAt',
    'idFarm',
    'idProducer',
    'name',
    'state',
    'totalArea',
    'updatedAt',
    'vegetationArea',
  ] as const
  $columns = FarmSchema.$columns
  @column()
  declare agriculturalArea: string
  @column()
  declare city: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idFarm: string
  @column()
  declare idProducer: string
  @column()
  declare name: string
  @column()
  declare state: string
  @column()
  declare totalArea: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vegetationArea: string
}

export class HarvestCropSchema extends BaseModel {
  static $columns = ['idCrop', 'idHarvest'] as const
  $columns = HarvestCropSchema.$columns
  @column()
  declare idCrop: string
  @column({ isPrimary: true })
  declare idHarvest: string
}

export class HarvestSchema extends BaseModel {
  static $columns = ['createdAt', 'idFarm', 'idHarvest', 'updatedAt', 'year'] as const
  $columns = HarvestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare idFarm: string
  @column({ isPrimary: true })
  declare idHarvest: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare year: number
}

export class ProducerSchema extends BaseModel {
  static $columns = [
    'city',
    'createdAt',
    'document',
    'documentType',
    'idProducer',
    'idUser',
    'name',
    'state',
    'updatedAt',
  ] as const
  $columns = ProducerSchema.$columns
  @column()
  declare city: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string
  @column()
  declare documentType: string
  @column({ isPrimary: true })
  declare idProducer: string
  @column()
  declare idUser: string
  @column()
  declare name: string
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'idUser',
    'name',
    'passwordHash',
    'role',
    'status',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare idUser: string
  @column()
  declare name: string
  @column()
  declare passwordHash: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
